services:
  app:
    restart: always
    volumes:
      - ../../src:/app/src
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${APP_PORT}:8000"

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -p 5432"]
      interval: 2s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    restart: always
    expose:
      - 5432

volumes:
  postgres_data:
